[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
pump_science = "AKsYAeh8GeE2dvhfiPGURaNzC7SEDkNgmbrcDkmf4Qsz"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/henry/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
