[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
pump_science = "BjbuCn9cWxLZFmRc7zQ4hwV45SyqZA5YSMKpvUUeeHvw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/henry/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
