[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
pump_science = "EjamzaR4XFnrUnuQAJDD5Eq92Fky9R7Ej4y52YZZgJ9z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/henry/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
