[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
pump_science = "HHst35aSCp2ZNpAi3pwogbtBo5k6bgazL9UbUoBhjisX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
