[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
pump_science = "J3nh6pDYtUbwZbGfTozRhHgPJnRVUR2aFAXCrqt9qo62"

[programs.mainnet]
pump_science = "J3nh6pDYtUbwZbGfTozRhHgPJnRVUR2aFAXCrqt9qo62"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "/Users/henry/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
